In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[ 0.21786905  0.18068086 -0.16956708 -0.22084376 -0.64708841]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.21786905  0.18068086 -0.16956708 -0.22084376 -0.64708841]


In [5]:
print(np.dot(a,a.T))

0.576360867073


In [6]:
a = np.random.randn(5,1)

In [7]:
print(a)

[[ 0.53067044]
 [-1.55386046]
 [-1.04750751]
 [ 0.86663798]
 [ 0.14261928]]


In [8]:
print(a.T)

[[ 0.53067044 -1.55386046 -1.04750751  0.86663798  0.14261928]]


In [9]:
print(np.dot(a,a.T))

[[ 0.28161112 -0.82458782 -0.55588128  0.45989916  0.07568384]
 [-0.82458782  2.41448234  1.62768051 -1.3466345  -0.22161047]
 [-0.55588128  1.62768051  1.09727199 -0.9078098  -0.14939477]
 [ 0.45989916 -1.3466345  -0.9078098   0.75106139  0.12359929]
 [ 0.07568384 -0.22161047 -0.14939477  0.12359929  0.02034026]]
